name: Deploy Frontend to Production (SWA)

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps (Production)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: client
          output_location: ""
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_VERSION: 20
          NEXT_PUBLIC_APP_NAME: ShipScan
